"""Added a starred column to exercises/lifts section

Revision ID: 7e209f544449
Revises: 169a04825fc7
Create Date: 2025-12-07 12:04:10.596607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e209f544449'
down_revision: Union[str, None] = '169a04825fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('is_starred', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'is_starred')
    # ### end Alembic commands ###
